version: 2
jobs:
    #Diadikasia build
    build:
        working_directory: ~/project
        docker:
            - image: circleci/node:8.16-jessie-browsers
        steps:
            - setup_remote_docker
            #Checkout sto teleutaio commit
            - checkout
            #Ektyposi minimatos sxetika me to branch to opoio ginetai to build job
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            #An yparxoun cached ta dependencies ginetai xrisi tous
            - restore_cache:
                keys:
                - coolcounterapp-dependencies-{{ checksum "package.json" }}
                - coolcounterapp-dependencies-
            #Egkatastasi ton aparaititon dependencies tis angular
            - run:
                name: Install local dependencies
                command: npm install
            #An ekteleitai proti fora, ginontai cache ta dependencies gia eksoikonomisi xronou
            - save_cache:
                key: coolcounterapp-dependencies-{{ checksum "package.json" }}
                paths:
                    - node_modules                
            #Ektelesi tou lint gia elegxo code styling
            - run:
                name: Linting
                command: npm run lint
            #Ektelesi ton diathesimon tests
            - run:
                name: Testing
                command: npm run test
            #Production build tis angular efarmogis
            - run:
                name: Building
                command: npm run build --prod
            #Dimiourgia docker image, tag tou image kai dimosieusi sto dockerhub
            - run:
                name: Dockerhub Publish
                command: |
                    docker build -t coolcounterapp .                    
                    docker tag coolcounterapp $DOCKER_HUB_USER_ID/coolcounterapp:$CIRCLE_SHA1
                    docker tag coolcounterapp $DOCKER_HUB_USER_ID/coolcounterapp:latest
                    docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
                    docker push $DOCKER_HUB_USER_ID/coolcounterapp:$CIRCLE_SHA1
                    docker push $DOCKER_HUB_USER_ID/coolcounterapp:latest
