version: 2

jobs:
    # The build job
    build:
        working_directory: ~/project
        docker:
            - image: circleci/node:8.16-jessie-browsers
        steps:
            # Checkout the code from the branch into the working_directory
            - checkout
            # Log the current branch
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            # Install project dependencies
            - run:
                name: Install local dependencies
                command: npm install
            # Lint the source code
            - run:
                name: Linting
                command: npm run lint
            # Test the source code
            - run:
                name: Testing
                command: npm run test
            # Build project with different configuration based on
            # the current branch
            - run:
                name: Building
                command: |
                    npm run build --prod
            #Publish to dockerhub
            - run:
                name: Dockerhub Publish
                command: |
                    sudo docker build -t coolcounterapp .                    
                    sudo docker tag coolcounterapp $DOCKER_HUB_USER_ID/coolcounterapp:$CIRCLE_SHA1
                    sudo docker tag coolcounterapp $DOCKER_HUB_USER_ID/coolcounterapp:latest
                    sudo docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
                    sudo docker push $DOCKER_HUB_USER_ID/coolcounterapp:$CIRCLE_SHA1
                    sudo docker push $DOCKER_HUB_USER_ID/coolcounterapp:latest        
