
version: 2
jobs:
  build:
    working_directory: /coolcounterapp
    docker:
      - image: node:8.16.0-jessie
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install-angular
          command: 'sudo npm install -g angular@7.3.0'
      - run:
          name: ng-lint
          command: 'ng lint'