
version: 2
jobs:
  build:
    working_directory: /coolcounterapp
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache nodejs
            npm install docker-compose
      - run:
          name: Run lint
          command: |
            docker-compose up -d
            docker-compose run coolcounterapp ng lint